theme: jekyll-theme-minimal
title: Intrepydd Guide
description: This site is the public documentation for Intrepydd, an ahead-of-time (AOT) compilation system for Python programmers who want faster code on current hardware, and also on future reconfigurable and heterogeneous systems.  Intrepydd is being developed in the DDARING project led by Georgia Tech in the DARPA Software Defined Hardware (SDH) program.
